// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    'intro',
    'quickstart',
    'auth',
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'chat-completions',
        'images',
        'models',
        {
          type: 'category',
          label: '视频生成接口 API',
          collapsed: false,
          link: {type: 'doc', id: 'video/overview'},
          items: [
            {
              type: 'category',
              label: '豆包 Seedance 视频生成',
              collapsed: false,
              link: {type: 'doc', id: 'video/seedance/overview'},
              items: [
                'video/seedance/create',
                'video/seedance/private-assets',
                'video/seedance/human-verification',
                'video/seedance/query',
                'video/seedance/list',
                'video/seedance/delete',
                'video/seedance/compatible',
              ],
            },
            {
              type: 'category',
              label: 'MiniMax-H3 视频生成',
              collapsed: false,
              link: {type: 'doc', id: 'video/h3/overview'},
              items: [
                'video/h3/create',
                'video/h3/regeneration',
                'video/h3/context-ir',
                'video/h3/query',
                'video/h3/list',
                'video/h3/delete',
              ],
            },
            {
              type: 'category',
              label: '可灵AI视频生成-新版接口',
              collapsed: true,
              items: [
                'video/kling-new',
                'video/kling-new/text-to-video',
                'video/kling-new/image-to-video',
                'video/kling-new/omni-video',
                'video/kling-new/motion-control',
                'video/kling-new/query',
              ],
            },
            {
              type: 'category',
              label: '可灵AI视频生成-原版接口',
              collapsed: true,
              items: [
                'video/kling',
                'video/kling/text-to-video',
                'video/kling/image-to-video',
                'video/kling/omni-video',
                'video/kling/multi-image-to-video',
                'video/kling/motion-control',
                'video/kling/multi-elements',
                'video/kling/extend',
                'video/kling/lip-sync',
                'video/kling/avatar',
                'video/kling/text-to-audio',
                'video/kling/video-to-audio',
                'video/kling/tts',
                'video/kling/voices',
                'video/kling/image-recognize',
                'video/kling/elements',
                'video/kling/effects',
              ],
            },
            {
              type: 'category',
              label: 'Vidu视频生成',
              collapsed: true,
              items: [
                'video/vidu-q3',
                'video/vidu/text-to-video',
                'video/vidu/image-to-video',
                'video/vidu/reference-to-video',
                'video/vidu/first-tail',
                'video/vidu/multiframe',
                'video/vidu/template',
                'video/vidu/template-story',
                'video/vidu/query',
              ],
            },
            {
              type: 'category',
              label: '万相视频生成',
              collapsed: true,
              items: [
                'video/wan3',
                'video/wan/text-to-video',
                'video/wan/image-to-video',
                'video/wan/reference-to-video',
                'video/wan/video-edit',
                'video/wan/first-tail',
                'video/wan/animate',
                'video/wan/speech',
                'video/wan/vace',
                'video/wan/query',
                'video/wan/wan3',
              ],
            },
          ],
        },
        'errors',
      ],
    },
  ],
};

export default sidebars;
